* 1
** атмосфера, мир
 книги, записки(просто объекты с подробным описанием), подсказки. 
 Описание местности куда входит. 
 Мысли героя. 
 log разным цветом смысловые слова и объекты выделять.
 Описание звуков действий.
 комнаты на карте можено сделать в виде разного пола и определения смены предыдущего.
** геймплей
 Открывать ключом - применение объекта?
 Закрытые контейнеры
 +когда идёт в стену, объект, писать в лог. (сообщения на событие движения в объект у объекта)
** инвентарь
 применение объекта(сделать обработчик взаимодействия предметов. вот откуда
 брать инфу? или так)
 положить объект(проверить пусто ли на текущем месте, добавить функцию
 выброса, удаляющую из инвентаря и добавляющая в объекты карты)
 ограничения на вместимость инвентаря
 +показвать описание объекта в инвентаре по выбору.
 показывать по ид ключа от чего они или что?
 комбинировать объект Комбинации для инструментов для открытия, загадки
* украшательства.
 Rend: glow(hard), loop bright flick(частично сделал, но нужно чтобы незвисимо было у разных объектов, и возможно по разным каналам rgb)
* 2
 спец объект - текстовое событие? просто событие?
 потом должно быть как то организовано в одном месте применение действия(предмета) к вещи. передавать фун действия в направлении.
 иерархия местоположения(локации) вида планета-материк-город-здание...
 ловить существ? магия?
* Refactor
писать тесты. 
выделить maingl
