* 1
** атмосфера, мир
 Описание местности куда входит. 
 Мысли героя. 
 Описание звуков действий.
 log разным цветом смысловые слова и объекты выделять.
 +комнаты на карте можено сделать в виде разного пола и определения смены предыдущего.
 книги, +записки(просто объекты с подробным описанием), подсказки. 
** геймплей
 !ломать.  !Дверь заклинило, не открыть (надо выбить)
      ломание зависит от силы и прочности. Сила есть текущая, масимальная,
      текущая после сна немного ниже - нужно сделать зарядку. Тренировка
      тренирует силу. Голод уменьшает силу, долгий - максимальную. Усталость
      уменьшает силу. Тренировки, ломание - устаёшь. Сила отдельно рук,
      корпуса, ног - тренировка тоже и требования для действий тоже.
 +спец дверь. +основа команды ломать. +части тела с силой. +учёт силы и пролом.
  !!изменения силы - ... +текущая и максимальная. ?зарядка.
  !усталость от каких действий?(фун усталости) (руки от крафта) 
  ноги устают от выбивания и хождения и уменьшается сила. но тренируется макс.
  мышечная усталость(частей) ментальная. Как обратная характеристика?  бодрость и выносливость?
  когда полностью устал - падаешь отдыхать, восстанавливая до критического минимума
       !Одежда, части тела, холод(хуже всё получается, сильнее есть)
       температура среды, замерзание. физические действия разогревают.
       голод. сытость - количество запасы энергии, пополняемые едой и
       расходуемые на действия - хождение, лом, открытие...
  !!Тренировка, меню персонажа и выбор частей тела. Трата выносливости и сытости. бег.

 Думание! - придумывание новых упражнений, применений инструментам...
 Отдых! Сон - восстанавливает в зависимости от количества, качества,
 усталости, еды...
 !комбинировать объект Комбинации для инструментов для открытия, загадки
        Так же можно дверь сломать инструментом (что для него требуется по телу и ингридиенты)
        взлом отвёрткой.
        В шкафу куча старой одежды, в другом рюкзак, отвёртка.
 !выводить характеристики объекта (режим исследования, посмотреть подробно)
 !режим простмотра характеристик вместо помощи - переключение
 !Выделить загрузку карты. загружать другую карту по объекту перехода(телепорта)
 !цвет сообщение в логе
                  
 Сделать упрощённое взаимодействие - идти на дверь - открыть, применить ключ если есть, автолут...
 тянуть, толкать, хватать и тащить
 map save, load
 усталость, сон
 магия с вводом заклинаний словами(можно запомнить и записать) заклинанием
 можно и сломать дверь и взорвать и отпереть и телепортировать.
** msg
      Интуиция подсказывает что нужно бы встать но ещё не проснулся.
Одеться. одежда лежить там где вы её оставили ложась спать - на стуле.
** +
 +выйти на балкон посмотреть что случилось.
 +спец объект - текстовое событие? просто событие? сообщение на движение и обыск уже есть.
 +События(сообщения...?) на определённые тики с начала, каждые N
 +Spawn player object
      как таки сделать применение объекта к объекту? ну типа таблицы (об1 на
      об2) = функця. Но как идентифицировать объекты? ID?!
      либо словарь словарей
      Может (потом) хранить это в yaml
 +применение объекта(сделать обработчик взаимодействия предметов. вот откуда брать инфу? или так)
 +Открывать ключом - применение объекта?
 +Закрытые контейнеры
 +когда идёт в стену, объект, писать в лог. (сообщения на событие движения в объект у объекта)
 +показвать описание объекта в инвентаре по выбору.
** инвентарь
 положить объект(проверить пусто ли на текущем месте, добавить функцию выброса, удаляющую из инвентаря и добавляющая в объекты карты)
 ограничения на вместимость инвентаря, количество, объём, вес. Рюкзаки
 показывать по ид ключа от чего они или что?
 контейнеры с множеством объектов
 генераторы объектов (расходников для загадок - реактивы, рецепты)
* украшательства.
 Rend: glow(hard), loop bright flick(частично сделал, но нужно чтобы незвисимо было у разных объектов, и возможно по разным каналам rgb)
 Туман неисследованных территорий.. поле видения? 
 Выключатели, свет, !освещение(предметы видимые только при свете, при уф свете)
   как сделать освещение. Нужна карта света - тайл освещён или нет (dict(x,y)) 
   пересчёт при движении, открытии(действиях?)
   от игрока, на радиус определить конечные тайлы и к ним линиями освещать
   тайлы пока не будет препятсвтия(непроходимое)?
     +переделать карту на (x,y)
     +переделать объекты в словарь(x,y)
     область видения
     +карта света и её воздействие на отрисовку
     расчёт карты света
* 2
 потом должно быть как то организовано в одном месте применение действия(предмета) к вещи. передавать фун действия в направлении.
* Refactor
писать тесты. 
выделить maingl
* идеи
** ближайшие
Пол и возможность его проломить и упасть, спустится на этаж ниже, копать землю.
В стене торчит ключ. Раздолбить молотком.
Для загадок: поворачивать краники, нажимать кнопки, вводить коды...
Рецепты в записках: Оказывается можно привязать камень к палке и получить подобие молотка.
Голод, еда, пищеварение, худение, вес, сила для действий.
- показатели персонажа - настроение(смайл), воля, силы(мышечная масса) жир,
  физические умения(ловкость) здоровье частей тела. Жажда, голод.
И хранить объекты в словарях с ключами = пара x y # Сделать функцию доступа к объекту.
фермерство! добыча воды
Вывод текста с переносом слов
** остальные
 иерархия местоположения(локации) вида планета-материк-город-здание...
 ловить существ? магия?
Лампочки - разобрать(разломать в тряпке) - осколки + клей + бумага = шкурка
Всеравно хочу выживастик с крафтом.
В чём смылс игры - в том же смысл жизни (героя) просто выживать,
развлекаться(кач, игры, еда...) исследовать(карта, местоназначаения, долгие
путешествия с непогодой, водные переправы, пустыни, горы, зима, лето, леса,
болота, ураганы, дожди, радиация, вулканы...) восстановить знания людей и отправиться заселять
другие миры.
жидкости и контейнеры, температура вещей и остывание (с коэффициентом)
Если будут большие локации то нужен ли скролинг.. будет ли всё одной большой
картой?
Написать преобразователь карты текстовой в список объектов с координатами
Давай делать дальше попупто доделывая и переделывая методы доступа и общую
организацию.
Создав однажды объект сам - можно будет через меню крафта его делать. (как и
постройки)
Исследования и проекты. Машины и заводы.
смерть от старости, забратый пришельцами добрыми. 
Невидимость, элексир бессмертия, бионика. (вредные и полезные книги и знания)
Из батареи можно слить немного воды.
Через какое то время все растения умрут дикие, кислород будет падать.
Метеориты. Надо прокачанной ботаникой восстанавливать биосферу. И животных(а
они начнут дичать и нападать)
Города со временем деградируют и распадутся, вещи обращаются в пыль, гниль,
грибы.
Духи... мир разрушен и снова освободилась магия, чем больше существ, тем
меньше магии.
Большинство дверей в доме закрыто, (50 этажей и крыша) лифт не работает. Эти
двери так просто не сломать и не взломать(сложно, но можно) 
А если знать заклинания жетвы своей крови, то можно прокачаться быстрее. И
так далее. Знать рецепты. Знать путь.
Потом будет world.maps[n] or world.maps.lostcity.building32.room31
