* 1
** атмосфера, мир
 Описание местности куда входит. 
 Мысли героя. 
 Описание звуков действий.
 log разным цветом смысловые слова и объекты выделять.
 +комнаты на карте можено сделать в виде разного пола и определения смены предыдущего.
 книги, +записки(просто объекты с подробным описанием), подсказки. 
** геймплей
 +Открывать ключом - применение объекта?
 +Закрытые контейнеры
 !!комбинировать объект Комбинации для инструментов для открытия, загадки
 +когда идёт в стену, объект, писать в лог. (сообщения на событие движения в объект у объекта)
 !Выделить загрузку карты. загружать другую карту по объекту перехода(телепорта)
 Сделать упрощённое взаимодействие - идти на дверь - открыть, применить ключ
 если есть, автолут...
      как таки сделать применение объекта к объекту? ну типа таблицы (об1 на
      об2) = функця. Но как идентифицировать объекты? ID?!
      либо словарь словарей
      Может (потом) хранить это в yaml
** инвентарь
 xприменение объекта(сделать обработчик взаимодействия предметов. вот откуда брать инфу? или так)
 положить объект(проверить пусто ли на текущем месте, добавить функцию выброса, удаляющую из инвентаря и добавляющая в объекты карты)
 ограничения на вместимость инвентаря
 показывать по ид ключа от чего они или что?
 +показвать описание объекта в инвентаре по выбору.
 контейнеры с множеством объектов
 генераторы объектов (расходников для загадок - реактивы, рецепты)
* украшательства.
 Rend: glow(hard), loop bright flick(частично сделал, но нужно чтобы незвисимо было у разных объектов, и возможно по разным каналам rgb)
 Туман неисследованных территорий.. поле видения? 
 Выключатели, свет, освещение(предметы видимые только при свете, при уф свете)
* 2
 спец объект - текстовое событие? просто событие?
 потом должно быть как то организовано в одном месте применение действия(предмета) к вещи. передавать фун действия в направлении.
 иерархия местоположения(локации) вида планета-материк-город-здание...
 ловить существ? магия?
* Refactor
писать тесты. 
выделить maingl
* идеи
В стене торчит ключ. Раздолбить молотком.
Голод, еда, пищеварение, худение, вес, сила для действий.
Рецепты в записках: Оказывается можно привязать камень к палке и получить
подобие молотка.
Тики времени
Для загадок: поворачивать краники, нажимать кнопки, вводить коды...
Вы проснулись в кровате, звучит сирена.
Интуиция подсказывает что нужно бы встать но ещё не проснулся.
Одеться. одежда лежить там где вы её оставили ложась спать - на стуле.
выйти на балкон посмотреть что случилось.
Многие здания разрушены, виднеются пожары, никого нет на улицах, машины
побросаны прямо на дорогах.
Вы начинаете беспокоится
Лампочки - разобрать(разломать в тряпке) - осколки + клей + бумага = шкурка

Всеравно хочу выживастик с крафтом.
В чём смылс игры - в том же смысл жизни (героя) просто выживать,
развлекаться(кач, игры, еда...) исследовать(карта, местоназначаения, долгие
путешествия с непогодой, водные переправы, пустыни, горы, зима, лето, леса,
болота, ураганы, дожди...) восстановить знания людей и отправиться заселять
другие миры.
Что надо:
- показатели персонажа - настроение, воля, силы(мышечная масса) жир,
  физические умения(ловкость) здоровье частей тела

