* 1
** атмосфера, мир
 Описание местности куда входит. 
 Мысли героя. 
 Описание звуков действий.
* геймплей
** еда
      Перевод энергии из долгой должен занимать время?
       долгий голод уменьшает максимальную силу
       часть еды сразу усваивается и может быть использована часть медленнее, часть очень медленно
       если запас текущий большой то постепенно переходит в долговремнный если мало то долгий переходит в текущий
        но долговременный тяжело носить и вред здоровью
       консервы. бутылки. вода из батарей и туалета.
       ещё потери воды зависят от? одежды? косвенно thirst
** Мир
 map save, load - сохранение состояния
 сделать карту хола и др. отразить другие комнаты
 автоматы с едой, монетки. без электричества
** Одежда, части тела, холод(хуже всё получается, сильнее есть)
       Одевание 
       защита от холода одежы, а от тепла? 
       +температура среды, 
       замерзание. 
       физические действия разогревают.  расходуемые на действия - хождение, лом, открытие...
** Тренировка тренирует силу. отдельно части тела. (трен выносливость)
        !Тренировка, меню персонажа и выбор частей тела. Трата выносливости и сытости. бег.

** объекты
 !комбинировать объект Комбинации для инструментов для открытия, загадки
        Так же можно дверь сломать инструментом (что для него требуется по телу и ингридиенты)
        взлом отвёрткой. Умение.
        В шкафу куча старой одежды, в другом рюкзак, отвёртка.
 разобрать цветочный горшок. удобрить почву своим навозом. посадить семена
 вытащенные из яблока (съел - остался огрызок) поливать. растить яблоню. и другие  (освещение, температура, вода)
 Готовка еды - крафт
 можно и сломать дверь и взорвать и отпереть и телепортировать.
 книги знаний рецептов и заклинаний и ложные
** quest
Список желаний(еды, отдыха, воды..) в том числе сходить куда-то.
  Думаю стоит сходить в город посмотреть что там осталось.
  Вам захотелось пойти в лес чтобы ...
лабиринт(из телепортов в начало) в самом начале, что было сном(и обучением)
В стене торчит ключ. Раздолбить молотком.
Для загадок: поворачивать краники, нажимать кнопки, вводить коды...
Рецепты в записках: Оказывается можно привязать камень к палке и получить подобие молотка.
** магия
   закл ускорения времени.
 магия с вводом заклинаний словами(можно запомнить и записать) заклинанием, команда "сказать"
      если неизвестно закл то и произнеся непонятно что делает, только потом.
      закл = слово, известность, фукнц, цель?
магические вещи(для заклинания, автозаряд, автокаст)
Опасные аномалии мира! стоячие заклятия. ловушки, телепорты
** другое
 Сон - восстанавливает в зависимости от количества, качества, усталости, еды...
 Думание! - придумывание новых упражнений, применений инструментам...
 Сделать упрощённое взаимодействие - идти на дверь - открыть, применить ключ если есть, автолут...
 тянуть, толкать, хватать и тащить
 Повреждения. себя и предметов. падение.
** время
 Время действий. Шаг - 0.25 сек. реальных. но игровое должно быть быстрее?  (добавить коэффициент)
 Хм - каждое действие занимает время и силы. может тут можно сделать данные
 (но потом сложны действия вроде крафта и взлома и магии будут тратить разное время)
** интерфейс
 log разным цветом смысловые слова и объекты выделять.
 упрощённные показатели - жажда, устал, сильно слабо..
 !выводить характеристики объекта (режим исследования, посмотреть подробно)
** Усталость
      +уменьшает силу. Тренировки, ломание - устаёшь.  (выносливость)
      усталость от каких действий?(фун усталости) (руки от крафта) 
      голова устаёт от чтения, магии, крафта, времени.
      баланс.
        а качество отдыха зависит от? объёма выносливости
** инвентарь
 положить объект(проверить пусто ли на текущем месте, добавить функцию выброса, удаляющую из инвентаря и добавляющая в объекты карты)
 ограничения на вместимость инвентаря, количество, объём, вес. Рюкзаки
 показывать по ид ключа от чего они или что?
 контейнеры с множеством объектов
 генераторы объектов (расходников для загадок - реактивы, рецепты)
** msg
      Интуиция подсказывает что нужно бы встать но ещё не проснулся.
Одеться. одежда лежить там где вы её оставили ложась спать - на стуле.
** +
+возможность пить пополня водный баланс
 -?+если голодать то вскоре быстрее начнёшь терять выносливость.
 +^!Объекты отдельным файлом? только базовые?
 +!^Лучше бы давать объектам нормальные имена и делать мапинг на карте символов в имена объектов
 +!Выделить загрузку карты. загружать другую карту по объекту перехода(телепорта)
 +walk_action
 +записки(просто объекты с подробным описанием), подсказки. 
 +комнаты на карте можено сделать в виде разного пола и определения смены предыдущего.
 +Голод уменьшает силу, 
      +возможность есть, съедобные объекты с энергией, пополнение энергий
      +переваривать еду требует силы тела(всего?).
      +от еды должны остваться остатки
+Сделать шрифт не квадратным а 8x16, отдельно?
 -голод. сытость - количество запасы энергии, пополняемые едой и
 -если поесть то сил сразу не прибавится - но можно будет потом восстановить
 -может выносливости не надо и достаточно силы? ну если она будет
 -постоянно уменьшатся то это не то, максимальную силу можно применять
 -много раз, только с усталостью она уменьшается немного и не до нуля.
 -есть текущая расходуемая энергия и запасы
+жажда. зависит от уставания и температуры. темп комнат, при какой
+меньше всего потерь жидкости? чем меньше, норма(1) при ~20 при 25(2)
+30(3) 15(0.5) но минимум = 0.1 (t**2)/400
+жажда усиливает усталость и ослабляет - Коэффициент уствания
+потеря жидкости при уставании с коэффициентом от температуры среды.
 +цвет сообщение в логе
 +Отдых если есть резерв энергии(съедено) который уменьшается(и постоянно) 
 +команду отдыха, принудительный отдых N раз
 +отдых тратит энергию на восстановление сил до минимума и выносливость
  +когда полностью устал - падаешь отдыхать, восстанавливая до критического минимума
  +ноги устают от выбивания и хождения и уменьшается сила. но тренируется макс.
  +мышечная усталость(частей) ментальная. Как обратная характеристика?  бодрость и выносливость?
  +фун устать. +уставать при действиях.
  +влияние усталости - уменьшение силы, тренировка силы и вын.
  +пусть пока линейно 1 вын на 0.1 силы
  +если силы ног мало то не ходить - отдых до минимума
 +спец дверь. +основа команды ломать. +части тела с силой. +учёт силы и пролом.
 +ломать.  +Дверь заклинило, не открыть (надо выбить)
 +ломание зависит от силы и прочности. Сила есть текущая, масимальная,
 +режим простмотра характеристик вместо помощи - переключение
 +!освещение(
   как сделать освещение. Нужна карта света - тайл освещён или нет (dict(x,y)) 
   пересчёт при движении, открытии(действиях?)
   от игрока, на радиус определить конечные тайлы и к ним линиями освещать
   тайлы пока не будет препятсвтия(непроходимое)?
     +переделать карту на (x,y)
     +переделать объекты в словарь(x,y)
     +карта света и её воздействие на отрисовку
     +расчёт карты света
 +выйти на балкон посмотреть что случилось.
 +спец объект - текстовое событие? просто событие? сообщение на движение и обыск уже есть.
 +События(сообщения...?) на определённые тики с начала, каждые N
 +Spawn player object
      как таки сделать применение объекта к объекту? ну типа таблицы (об1 на
      об2) = функця. Но как идентифицировать объекты? ID?!
      либо словарь словарей
      Может (потом) хранить это в yaml
 +применение объекта(сделать обработчик взаимодействия предметов. вот откуда брать инфу? или так)
 +Открывать ключом - применение объекта?
 +Закрытые контейнеры
 +когда идёт в стену, объект, писать в лог. (сообщения на событие движения в объект у объекта)
 +показвать описание объекта в инвентаре по выбору.
* украшательства.
Цветные показатели цифровые(от значения зависит, красный - дело плохо)
Выровнять буквы.
 Rend: glow(hard), loop bright flick(частично сделал, но нужно чтобы незвисимо было у разных объектов, и возможно по разным каналам rgb)
 Туман неисследованных территорий.. поле видения? 
 Выключатели, свет, источники света, дневной свет и темнота ночью
 область видения
 предметы видимые только при свете, при уф свете)
 прогресс полосочки
* Refactor
 потом должно быть как то организовано в одном месте применение действия(предмета) к вещи. передавать фун действия в направлении.
писать тесты. 
выделить maingl
думать над отвязкой от состояния глоб. - сначала чистая функция, потом грязная обёртка
 !!!Всё же думаю стоит писать сначала функцию чистую, которая обрабатывает
 данные переданные(меняет может) а для неё функцию которая её вызывает и
 обрабатывает результат(enum? как проще) и уже меняет состояние мира. чистые
 можно начать тестировать.
* идеи
выносливость это энергия груп мышц. энергия это запасы еды
** ближайшие
 После жизненное сообщение статиситки(время..)
Голод, еда, пищеварение, худение, вес, сила для действий.
- показатели персонажа - настроение(смайл), воля, силы(мышечная масса) жир,
  физические умения(ловкость) здоровье частей тела. Жажда, голод.
+И хранить объекты в словарях с ключами = пара x y # Сделать функцию доступа к объекту.
фермерство! добыча воды
Вывод текста с переносом слов
Пол и возможность его проломить и упасть, спустится на этаж ниже, копать землю.
** остальные
Ближайший геймплей - проснуться, узнать что чтото случилось, одеться поесть
попить, выбраться из спальни, решить загадочку открыв входную дверь и собрав
немного провизии и инструментов. Бродить по дому(доступна крыша, лестницы,
подъезд). выход во двор. ...? что тут, где мы. рядом пара домов похожих, улица
на север - в лес, на юг в город, запад - поле и дорога в даль, восток - река,
мост, дорога в даль. Что тут можно достигнуть? стройматериалы в лесу
много вещей в магазах в городе. поля культур(а какое время года и
температура, погода, время дня) вода в реке, научиться выживать
  вот теперь незнаю что делать то :)
Канализация, подземелья дальше вниз и инопланетяне маги остатки разрушившие
мир, где можно научаться.
 иерархия местоположения(локации) вида планета-материк-город-здание...
 ловить существ? магия?
Лампочки - разобрать(разломать в тряпке) - осколки + клей + бумага = шкурка
Из батареи можно слить немного воды.
Большинство дверей в доме закрыто, (50 этажей и крыша) лифт не работает. Эти
двери так просто не сломать и не взломать(сложно, но можно) 
Всеравно хочу выживастик с крафтом и магией и временной петлёй
В чём смылс игры - в том же смысл жизни (героя) просто выживать,
развлекаться(кач, игры, еда...) исследовать(карта, местоназначаения, долгие
путешествия с непогодой, водные переправы, пустыни, горы, зима, лето, леса,
болота, ураганы, дожди, радиация, вулканы...) восстановить знания людей и отправиться заселять
другие миры.
Через какое то время все растения умрут дикие, кислород будет падать.
Метеориты. Надо прокачанной ботаникой восстанавливать биосферу. И животных(а
они начнут дичать и нападать)
жидкости и контейнеры, температура вещей и остывание (с коэффициентом)
Если будут большие локации то нужен ли скролинг.. будет ли всё одной большой картой?
Написать преобразователь карты текстовой в список объектов с координатами
Давай делать дальше попупто доделывая и переделывая методы доступа и общую организацию.
Создав однажды объект сам - можно будет через меню крафта его делать. (как и постройки)
Исследования и проекты. Машины и заводы.
смерть от старости, забратый пришельцами добрыми. 
Невидимость, элексир бессмертия, бионика. (вредные и полезные книги и знания)
Города со временем деградируют и распадутся, вещи обращаются в пыль, гниль, грибы.
Духи... мир разрушен и снова освободилась магия, чем больше существ, тем меньше магии.
А если знать заклинания жетвы своей крови, то можно прокачаться быстрее. И
так далее. Знать рецепты. Знать путь.
Потом будет world.maps[n] or world.maps.lostcity.building32.room31
