Система с состояниями\режимами - фм, фм для видео, напоминалка, терминал, браузер...
  хранение ссылок и их открытие установленной прогой(xlinks2)
* Сама система
- строка состояния режима. режимов много и надо сразу разработать и
  оттестировать создание и работу режимов, переключение, назначение функций.
  в режиме будут подсостояния. надо наверно сохранять внтуреннее состояние,
  при переключении режима внутр.сост. не меняется. ид состояния?
** status
с датой, свободной памятью, свопом, в %, загрузкой цп, дисковой загрузкой... поискать что ещё можно вывести, статус системы. текстовую. потом сделать гуёвую на основе. Логи, процессы.
- режим назначения клавиш. Сразу делать с расчётом на конфигурируемость клав.
* fm
- постройка дерева файловой системы, с цветами типами файлов, размером каталогов.
- Количество раз открытий файла считать и выводить\показывать цветом(чтобы знать что читаю часто, какие серии смотрел, что не открывал даже)
* remind
возможность ставить будильник с сообщением.
  на конекретную дату время
  с повтором
  на каждые интервалы времени(день, час...)
возможность отмены, выключения, удаления будильников.
* zametki
возможность делать записки.
  иерархический блокнот
тренировки
* sync all data
* webcat
алг:
  взять страницу
  выбрать все ссылки на тот же домен, блоки текста, картинки, видео
  отсортировать, по строке, размеру текста, размеру
  сгруппировать в категории рекурсивно
    ссылки вида domain.omn/some/ano/hhh.aaa
    положить в категорию(словарь, дерево?) some, в ней категорию ano, узел hhh(title)
    категорию выделять если там более N(10?) ссылок, остальные в спец категорию
  выводить отсортированно сначала самые крупные категории
  так построить дерево\сеть сайта(как циклы избежать)
  но можно показывать по одной странице, и только по требованию загружать узел
  ввыводить в виде дерева
  или сразу грузить весь сайт и сохранять в файл\бд и так иметь список сайтов таких
  добавить возможность открывать ссылки в браузере
  а картинки загружать и открывать
  и текст читать
  Обновление сайта
  автозагрузка определённых узлов и закачка нового. 
    напр с канала список watch видео и качать новые.

хочу: (google rutr github habr gt)
webcat google some_query
>
1. http://url1.com/
2. ...
webcat rutracker some_serial
> 1. name 1 ...
webcat samlib ...

Как же это делать? можно использовать спец. апи гугла напр. но это привязка и на не все
сайты распрастраняется? значит умное выковыривание html? по блокам ссылки, h2 h3
> footer - link1 link2
> body - link1 ...
С фильтрацией
добавить в остлеживание обновлений(серий)

Приложение - на сервере очередь команд. приложение на телефоне добавляет, на пк считывает и выполняет.
Как можно с компа на фон перекинуть текст без подкл и инета? камера, ...
scan video files and open it, count times, last view
