bulletImage = 'objects/bullet.png'
inventoryBG = 'objects/inventoryBG.png'
cellImg = 'objects/inventoryCell.png'
particleDefault = 'objects/particleR.png'
particleBlood = 'objects/particleBlood.png'
none = 'objects/none.png'
defaultBlock = 'objects/block1.png'
bg = 'objects/nightSky0.png'
hpbarimg = 'objects/hpbar.png'
hpbarrectimg = 'objects/hpbarrect.png'

playerAnimRight = ['objects/walkmanR0.png','objects/walkmanR1.png','objects/walkmanR2.png']
playerAnimLeft = ['objects/walkmanL0.png','objects/walkmanL1.png','objects/walkmanL2.png']
playerAnimUp = ['objects/walkmanU0.png','objects/walkmanU1.png','objects/walkmanU2.png']
playerAnimStand = ['objects/stand0.png','objects/stand1.png','objects/stand2.png']
playerAnimStandR = ['objects/standR0.png','objects/standR1.png']
playerAnimStandL = ['objects/standL0.png','objects/standL1.png']
playerAnimKickL = ['objects/kick0.png','objects/kick1.png','objects/kick2.png', 'objects/kick3.png']
playerAnimKickR = ['objects/kickR0.png','objects/kickR1.png','objects/kickR2.png', 'objects/kickR3.png']
